apiVersion: v1
kind: Service
metadata:
  name: hcl-hackathon-service
spec:
  type: LoadBalancer
  selector:
    app: hcl-hackathon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerSourceRanges:
    - 0.0.0.0/0
