apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hcl-hackathon-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: hcl-hackathon-group
spec:
  rules:
    - host: hcl-hackathon.example.com # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hcl-hackathon-service
                port:
                  number: 80
