name: Deploy to AWS ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init  # ✅ No need to change directory

      - name: Check Terraform Configuration
        run: terraform plan

      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  docker_build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform  # ✅ Terraform must complete first
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Build and Push Docker Image to ECR
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPO }} .
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO }}
          docker tag ${{ secrets.AWS_ECR_REPO }}:latest ${{ secrets.AWS_ECR_REPO }}:latest
          docker push ${{ secrets.AWS_ECR_REPO }}:latest

  deploy:
    name: Deploy to ECS Fargate
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Apply ECS Deployment Manifest
        run: |
          cd manifest.com  # ✅ Navigate to correct manifest directory
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml

      - name: Force New ECS Fargate Deployment
        run: |
          aws ecs update-service --cluster hcl-hackathon-devops-kamal-ECSFargate \
          --service hcl-service \
          --force-new-deployment
